@host=http://localhost:5133
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Yousef",
    "lastName": "Raid",
    "email": "yraid@utb.cz",
    "password": "yousef",
    "phoneNumber":"+420 728 728 728"
}