@host=http://localhost:5133
GET  {{host}}/todo/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyODc0M2NkMy1kN2I2LTQzNTEtOGE1NS0yNTY4MmQwNWExM2MiLCJnaXZlbl9uYW1lIjoiQWhtZWQiLCJmYW1pbHlfbmFtZSI6IkhhbWlkIiwiUGhvbmVOdW1iZXIiOiIxMjM0NTY3ODkiLCJKd3RSZWdpc3RlcmVkQ2xhaW1OYW1lcy5KdGkiOiI3YjQzOTk5NS00ZjMwLTQ0MzItYWY4ZC1kZTMzNmFiYTk1NDUiLCJleHAiOjE2NjU1Mjg2ODgsImlzcyI6IlRvRG8iLCJhdWQiOiJUb0RvIn0.5ZRALPaNcXzgDVzXHwuYRirCrLUBIXQQ7WoncNw9B98