@host=http://localhost:5133
GET  {{host}}/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OWU1YWI5My04NjIzLTRiZmQtODhhYi03ZjMxMGQ0YTUxNzEiLCJnaXZlbl9uYW1lIjoiQWhtZWQiLCJmYW1pbHlfbmFtZSI6IlRhaGEiLCJQaG9uZU51bWJlciI6Iis0MjAgNzI4IDcyOCA3MjgiLCJKd3RSZWdpc3RlcmVkQ2xhaW1OYW1lcy5KdGkiOiI0ZTgxYzU1ZC0xOGRiLTQxMjYtODM3ZC01NDc2YjFiZWE4NWQiLCJleHAiOjE2NjM0MzQyNzksImlzcyI6IlRvRG8iLCJhdWQiOiJUb0RvIn0.y3QKYIZnyHxI1Ww0VS95VUnoS-8tvrIGLWUKPwmTfDQ